"""Remove nitrite column from WaterParameter model

Revision ID: 19838cd41450
Revises: e1250492bb63
Create Date: 2023-06-24 21:42:16.484963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19838cd41450'
down_revision = 'e1250492bb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_parameters', schema=None) as batch_op:
        batch_op.drop_column('nitrite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nitrite', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
