"""Add 'date-recorded' column to WaterParameter model

Revision ID: a08cd5ca7fd7
Revises: f6daa2185597
Create Date: 2023-06-23 20:32:01.905979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08cd5ca7fd7'
down_revision = 'f6daa2185597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_recorded', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_parameters', schema=None) as batch_op:
        batch_op.drop_column('date_recorded')

    # ### end Alembic commands ###
