"""Remove username column from User model

Revision ID: c24fbe99dd66
Revises: f0b3fe4b83f6
Create Date: 2023-06-21 09:37:37.247584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24fbe99dd66'
down_revision = 'f0b3fe4b83f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=254),
               nullable=False)
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
