"""empty message

Revision ID: f6daa2185597
Revises: 4487d836f00f
Create Date: 2023-06-22 11:01:25.942938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6daa2185597'
down_revision = '4487d836f00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aquariums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aquariums', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
